### PR TITLE
Filter cells and genes

### PR DESCRIPTION
**Pull request by bellenger-l**
Began to implement a general Rscript that filter low quality genes and cells.
Only output for now is a pdf with plots

### CODE REVIEW

**Comment by drosofff** [comment]
@bellenger-l no you need review for merging at this stage ? Have you the rights for merging ?

**Comment by drosofff** [comment]
@bellenger-l I just saw that your started to implement a galaxy wrapper here. I know that it is an option. But after reflecting I think that it is better to develop the galaxy wrapper right in tools-artbio. At least to be discussed

**Comment by bellenger-l** [comment]
@drosofff I add a test file with mitochondrial genes in order to test the script that include mito genes.
I think it's better to wait for the galaxy wrapper, I'll do it in tool-artbio.

**Comment by drosofff** [comment]
👍 You're welcome to spin off a branch in tools-artbio. Do not hesitate to start with the tests ! This is the right way in CI.

**Comment by bellenger-l** [comment]
Avec cette méthode ? : https://jeffvautin.com/2015/01/spinning-off-a-git-repo/

**Comment by bellenger-l** [comment]
Can I close this PR now ? Duplicate with filter-cells in tools-artbio

**Comment by drosofff** [comment]
Sure ! The other one too, imho

**Comment by bellenger-l** [comment]
Ok, closing this PR !

**Pull request closed without merging**
